'use client';
import { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';
import { Upload } from 'lucide-react';
import * as XLSX from 'xlsx';

// 1. Define types
interface Slot {
  id: number;
  created_at: string;
  generated_by: string;
  campaign_type: string;
  total_count: number;
  duration_hours: number;
  interval_minutes: number;
}

interface FailedRow {
  Contact_Number?: string | number;
}

export default function SlotManager({ onRefresh }: { onRefresh: () => void }) {
  const [slots, setSlots] = useState<Slot[]>([]);
  // 2. We use this number to trigger a reload safely
  const [refreshKey, setRefreshKey] = useState(0);

  // 3. The function is now INSIDE useEffect, so no "missing dependency" warnings!
  useEffect(() => {
    const fetchSlots = async () => {
      const { data } = await supabase
        .from('slots')
        .select('*')
        .order('created_at', { ascending: false });
        
      if (data) setSlots(data as Slot[]);
    };

    fetchSlots();
  }, [refreshKey]); // Only re-runs when refreshKey changes

  const handleFailedUpload = async (slotId: number, e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (event) => {
      const bstr = event.target?.result;
      if (typeof bstr !== 'string') return;

      const wb = XLSX.read(bstr, { type: 'binary' });
      const data = XLSX.utils.sheet_to_json<FailedRow>(wb.Sheets[wb.SheetNames[0]]);
      
      const failedNumbers = data.map(r => String(r.Contact_Number || '').trim());

      const { data: contacts } = await supabase
        .from('contacts')
        .select('id, phone_number')
        .in('phone_number', failedNumbers);

      if (!contacts || contacts.length === 0) {
        alert('No matching numbers found');
        return;
      }

      const contactIds = contacts.map(c => c.id);

      const { error } = await supabase
        .from('contact_slots')
        .delete()
        .eq('slot_id', slotId)
        .in('contact_id', contactIds);

      if (!error) {
        alert(`Removed ${contactIds.length} failed numbers from Slot ${slotId}. Stats updated.`);
        onRefresh(); 
        setRefreshKey(prev => prev + 1); // This triggers the useEffect above to reload
      } else {
        alert('Error removing contacts');
      }
    };
    reader.readAsBinaryString(file);
  };

  return (
    <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
      <h2 className="font-bold text-lg mb-4">Slot Management</h2>
      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
            <thead className="bg-slate-50 border-b">
                <tr>
                    <th className="p-3">Slot ID</th>
                    <th className="p-3">Type</th>
                    <th className="p-3">Count</th>
                    <th className="p-3">Generated By</th>
                    <th className="p-3">Actions</th>
                </tr>
            </thead>
            <tbody>
                {slots.map(s => (
                    <tr key={s.id} className="border-b hover:bg-slate-50">
                        <td className="p-3 font-mono text-slate-500">#{s.id}</td>
                        <td className="p-3"><span className="px-2 py-1 bg-blue-50 text-blue-700 rounded text-xs font-bold">{s.campaign_type}</span></td>
                        <td className="p-3 font-bold">{s.total_count}</td>
                        <td className="p-3 text-slate-500">{s.generated_by || 'System'}</td>
                        <td className="p-3">
                            <label className="cursor-pointer text-xs bg-rose-50 text-rose-600 px-3 py-1 rounded hover:bg-rose-100 flex items-center w-fit gap-1">
                                <Upload className="w-3 h-3" /> Return Failed
                                <input type="file" className="hidden" onChange={(e) => handleFailedUpload(s.id, e)} />
                            </label>
                        </td>
                    </tr>
                ))}
            </tbody>
        </table>
      </div>
    </div>
  );
}